jsf:
  projectStage: Development
  facelets-skip-comments: true
  interpret-empty-string-submitted-values-as-null: true
  partialStateSaving: true
  serializeServerState: true
  stateSavingMethod: server
  mojarra:
    enable-missing-resource-library-detection: true
  primefaces:
    font-awesome: true
    theme: afterdark
#      privateCaptchaKey: myPrivateCaptchaKey
#      publicCaptchaKey: myKey
  facelets-buffer-size: 10485760
  default-suffix: .xhtml
  datetimeconverter-default-timezone-is-system-timezone: true
  validate-empty-fields: auto

server:
  port: 8080
  servlet:
    session:
      timeout: 1800s
      persistent: false
  http2:
    enabled: true
  use-forward-headers: true

management:
  server:
    port: 9000
  endpoints:
    enabled-by-default: true

spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  mail:
    host: 10.1.1.1
    port: 25
    default-encoding: UTF-8
  jmx:
    default-domain: jxmdomain

info:
  app:
    name: Joinfaces test
    description: Just a test
    version: 1.0.0
